In [4]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt 
import seaborn as sns

import joblib


%matplotlib inline

ModuleNotFoundError: No module named 'pandas'

### Parsing the caliberated CFLIB library data in dataframe using tab delimiter

In [ ]:
df = pd.read_csv("asu (2).tsv", delimiter = "\t", encoding = "latin1")

In [ ]:
df.head()

,n_Name,Name,SpType,Teff,e_Teff,log(g),e_log(g),[Fe/H],e_[Fe/H],r_[Fe/H],SimbadName,_RA,_DE
0,,,,K,K,[cm/s2],[cm/s2],[Sun],[Sun],,,deg,deg
1,-,----------,------------,-----,----,-----,-----,-----,-----,--,----------,---------,---------
2,,HD000249,K1IV,4757,28,2.88,0.09,-0.29,0.06,0,HD000249,001.84401,+26.45060
3,,HD000358,B8IVmnp...,12307,180,4.14,0.07,0.38,0.09,0,HD000358,002.09691,+29.09043
4,,HD000400,F8IV,6215,45,4.18,0.07,-0.24,0.07,0,HD000400,002.17058,+36.62712

In [ ]:
df.drop([0,1], inplace = True)

In [ ]:
df.reset_index(drop = True, inplace= True)

In [ ]:
df.head()

,n_Name,Name,SpType,Teff,e_Teff,log(g),e_log(g),[Fe/H],e_[Fe/H],r_[Fe/H],SimbadName,_RA,_DE
0,,HD000249,K1IV,4757,28,2.88,0.09,-0.29,0.06,0,HD000249,001.84401,+26.45060
1,,HD000358,B8IVmnp...,12307,180,4.14,0.07,0.38,0.09,0,HD000358,002.09691,+29.09043
2,,HD000400,F8IV,6215,45,4.18,0.07,-0.24,0.07,0,HD000400,002.17058,+36.62712
3,,HD000417,K0III,4858,33,2.45,0.10,-0.30,0.08,0,HD000417,002.21724,+25.46298
4,,HD000693,F5V,6221,41,4.14,0.06,-0.34,0.06,0,HD000693,002.81607,-15.46798

#### Testing the interpolator pipeline

In [ ]:
INTERPOLATOR_MODEL = 'RF_base_model_pvk.sav'
STANDARD_SCALER = 'rf_standard_scale_pvk.sav'

In [ ]:

# import sklearn.preprocessing
# import sklearn.ensemble
# import sklearn.tree
# import sklearn.externals
# import sklearn.externals
# import sklearn

# # Patch the missing module path
# import sys
# import types

# sklearn_externals = types.ModuleType("sklearn.externals")
# sklearn_externals.joblib = joblib


# # Create a fake 'sklearn.preprocessing.data' module pointing to sklearn.preprocessing
# sys.modules['sklearn.preprocessing.data'] = sklearn.preprocessing
# sys.modules["sklearn.ensemble.forest"] = sklearn.ensemble
# sys.modules["sklearn.tree.tree"] = sklearn.tree
# sys.modules["sklearn.externals.joblib"] = sklearn.externals
# sys.modules['sklearn.externals.joblib.numpy_pickle'] = joblib.numpy_pickle

from sklearn.externals import joblib
model = joblib.load("RF_base_model_pvk.sav")
print(type(model))

TypeError: an integer is required (got type bytes)